title: Digital Payment Meetup Kigali
description: The Digital Payments Meetup is an informal event to discuss the state and the future of payments in Rwanda and the whole continent.

url: https://digital-payments-meetup-kigali.5apps.com
baseurl: "" # set this to the root of you site when deployed
paginate_path: "posts/page:num/"

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   email: hello@michaelbumann.com

stamplay: 
  app_id: 'kigalipaymentmeetup'

google_analytics: ""
